"use client";

import Link from "next/link";
import { ArrowLeftRight, ArrowRight, Award, CalendarDays, Crown, Library, ListPlus, LoaderCircle, ShieldAlert, Sparkles, Trophy, UsersRound } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";

import { PageHeading } from "@/components/page-heading";
import { apiFetch, PublicLeagueOverview, PublicOverviewTransaction } from "@/lib/api";

export function LeagueOverviewPage() {
  const [data, setData] = useState<PublicLeagueOverview | null>(null);
  const [error, setError] = useState("");
  useEffect(() => {
    let cancelled = false;
    apiFetch<PublicLeagueOverview>("/league-history/overview")
      .then(value => { if (!cancelled) setData(value); })
      .catch(reason => { if (!cancelled) setError(reason instanceof Error ? reason.message : "Could not load league overview."); });
    return () => { cancelled = true; };
  }, []);
  if (error) return <><Heading /><State title="League overview unavailable" detail={error} /></>;
  if (!data) return <><Heading /><Loading /></>;
  return <><Heading /><div className="space-y-7">
    <section className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><Champion data={data} /><Podium data={data} /></section>
    <Panel title="Current managers" icon={<UsersRound />} action="View all teams" href="/league/teams">{data.current_managers.length ? <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{data.current_managers.map(manager => <Link key={manager.id} href={`/league/teams/${manager.id}`} className="flex items-center justify-between gap-3 rounded-xl bg-white/[.03] px-4 py-3 hover:bg-white/[.055]"><span className="min-w-0"><strong className="block truncate">{manager.display_name}</strong><span className="block truncate text-xs text-slate-500">{manager.team_name ?? "No current team name"}</span></span><ArrowRight className="h-4 w-4 shrink-0 text-slate-700" /></Link>)}</div> : <Empty text="No active manager profiles are configured." />}</Panel>
    <section className="grid gap-5 xl:grid-cols-2"><Activity title="Latest trades" href="/league/trades" items={data.latest_trades} /><Activity title="Latest waiver activity" href="/league/waivers" items={data.latest_waivers} /></section>
    <Panel title="All-time headline records" icon={<Trophy />} action="See every record" href="/league/records">{data.headline_records.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{data.headline_records.map(record => <Link href="/league/records" key={record.key} className="rounded-xl bg-white/[.03] p-4 hover:bg-white/[.055]"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-slate-500">{record.label}</p><p className="mt-2 text-2xl font-black text-primary">{record.entries[0]?.value.toLocaleString(undefined, { maximumFractionDigits: 2 })}</p><p className="mt-1 truncate text-xs text-slate-400">{record.entries.map(entry => entry.manager_name).join(" · ")}</p>{record.tied && <p className="mt-1 text-[10px] font-bold uppercase tracking-[.08em] text-slate-600">Tied record</p>}</Link>)}</div> : <Empty text="Headline records will appear after history is imported." />}</Panel>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Recent weekly highlights" icon={<Award />}>{data.recent_highlights.length ? <div className="divide-y divide-white/6">{data.recent_highlights.map(item => <Link key={`${item.year}-${item.id}`} href={`/league/seasons/${item.season_id}`} className="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><span className="min-w-0"><strong className="block truncate text-sm">{item.category}</strong><span className="block truncate text-xs text-slate-500">{item.year} · Week {item.week} · {item.player_name ?? item.manager_name ?? item.detail ?? "League highlight"}</span></span><span className="shrink-0 text-sm font-black text-primary">{formatHighlightValue(item.value)}</span></Link>)}</div> : <Empty text="No calculated or manual weekly highlights yet." />}</Panel><Panel title="Last-place punishment" icon={<ShieldAlert />}>{data.punishment ? <Link href={`/league/seasons/${data.punishment.season_id}`} className="block rounded-xl bg-red-400/[.06] p-4"><p className="text-xs font-bold uppercase tracking-[.1em] text-red-300">{data.punishment.year} · {data.punishment.manager_name}</p><p className="mt-2 font-bold">{data.punishment.title}</p></Link> : <Empty text="No punishment has been entered." />}</Panel></section>
    <section className="lg:hidden"><h2 className="mb-4 text-sm font-bold uppercase tracking-[.16em] text-slate-500">Explore the league</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><QuickLink href="/league/teams" label="Teams" icon={<UsersRound />} /><QuickLink href="/league/seasons" label="Seasons" icon={<Library />} /><QuickLink href="/league/records" label="Records & fun facts" icon={<Sparkles />} /><QuickLink href="/league/trades" label="Trades" icon={<ArrowLeftRight />} /><QuickLink href="/league/waivers" label="Waiver wire" icon={<ListPlus />} /><QuickLink href="/league" label="League overview" icon={<CalendarDays />} /></div></section>
  </div></>;
}

function Heading() { return <PageHeading eyebrow="BTB archive" title="League overview">Champions, managers, recent activity, records, and the stories behind the league.</PageHeading>; }
function Champion({ data }: { data: PublicLeagueOverview }) { return <section className="relative overflow-hidden rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/[.16] to-card p-4 sm:p-5"><Crown className="absolute -right-3 -top-3 h-24 w-24 text-primary/[.08]" /><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Current champion</p>{data.champion ? <div className="relative mt-4"><Link href={`/league/teams/${data.champion.manager_id}`} className="text-2xl font-black hover:text-primary">{data.champion.manager_name}</Link><Link href={`/league/seasons/${data.champion.season_id}`} className="mt-1 block text-sm text-slate-400">{data.champion.year} champion</Link></div> : <p className="relative mt-4 text-sm text-slate-500">No championship placement has been entered.</p>}</section>; }
function Podium({ data }: { data: PublicLeagueOverview }) { return <Panel compact title={data.podium[0] ? `${data.podium[0].year} podium` : "Most recent podium"} icon={<Trophy />}>{data.podium.length ? <div className="grid gap-2 sm:grid-cols-3">{data.podium.map(item => <Link key={item.manager_id} href={`/league/teams/${item.manager_id}`} className="rounded-xl bg-white/[.03] p-3"><span className="text-xl font-black text-primary">#{item.placement}</span><strong className="mt-1 block truncate">{item.manager_name}</strong></Link>)}</div> : <Empty text="No podium placements have been entered." />}</Panel>; }
function Activity({ title, href, items }: { title: string; href: string; items: PublicOverviewTransaction[] }) { return <Panel title={title} action="View all" href={href}>{items.length ? <div className="divide-y divide-white/6">{items.map(item => <Link key={item.id} href={href} className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0"><span className="min-w-0"><strong className="block truncate text-sm">{item.manager_names.join(" · ") || "Manager unavailable"}</strong><span className="block text-xs text-slate-500">{item.season ?? "Unknown season"} · Week {item.week} · {labelType(item.transaction_type)}</span></span><span className="shrink-0 rounded-full bg-white/5 px-2 py-1 text-[10px] font-bold uppercase text-slate-400">{item.status}</span></Link>)}</div> : <Empty text={`No ${title.toLowerCase()} have been imported.`} />}</Panel>; }
function Panel({ title, icon, action, href, children, compact = false }: { title: string; icon?: ReactNode; action?: string; href?: string; children: ReactNode; compact?: boolean }) { return <section className={`rounded-2xl border border-white/8 bg-card ${compact ? "p-4 sm:p-5" : "p-5 sm:p-6"}`}><header className={`${compact ? "mb-3" : "mb-5"} flex items-center justify-between gap-4`}><div className="flex items-center gap-2"><span className="text-primary [&_svg]:h-4 [&_svg]:w-4">{icon}</span><h2 className="font-bold">{title}</h2></div>{action && href && <Link href={href} className="text-xs font-semibold text-slate-500 hover:text-primary">{action}</Link>}</header>{children}</section>; }
function QuickLink({ href, label, icon }: { href: string; label: string; icon: ReactNode }) { return <Link href={href} className="flex items-center gap-3 rounded-xl border border-white/8 bg-card px-4 py-3 hover:border-primary/30"><span className="text-primary [&_svg]:h-4 [&_svg]:w-4">{icon}</span><strong className="flex-1 text-sm">{label}</strong><ArrowRight className="h-4 w-4 text-slate-700" /></Link>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed border-white/10 p-5 text-center text-sm text-slate-500">{text}</p>; }
function Loading() { return <div className="grid min-h-64 place-items-center rounded-2xl border border-white/8 bg-card"><LoaderCircle className="h-6 w-6 animate-spin text-primary" /></div>; }
function State({ title, detail }: { title: string; detail: string }) { return <div className="rounded-2xl border border-white/8 bg-card p-10 text-center"><h2 className="text-xl font-bold">{title}</h2><p className="mx-auto mt-2 max-w-lg text-sm text-slate-400">{detail}</p></div>; }
function labelType(value: string) { return value === "free_agent" ? "Free agent" : value.charAt(0).toUpperCase() + value.slice(1); }
function formatHighlightValue(value: number | null) { return value === null ? "—" : value.toLocaleString(undefined, { maximumFractionDigits: 2 }); }
