"use client";

import { Bot, Bookmark, BriefcaseBusiness, Building2, ChevronDown, ChevronUp, FileText, HelpCircle, History, Home, Inbox, Layers3, MessageSquare, Search, Tags, Trophy, Users } from "lucide-react";

import { Switch } from "@/components/ui/switch";
import { PTGWriteup } from "@/lib/api";

export function PTGOTWWorkMode({ writeup, onExit }: { writeup: PTGWriteup; onExit: () => void }) {
  return <div className="fixed inset-0 z-[100] overflow-y-auto bg-white font-[Arial,Helvetica,sans-serif] text-[#232629]">
    <div className="border-b-[3px] border-[#f48024] bg-[#333] px-4 py-3 text-center text-xs text-white"><span className="font-semibold">Developer update:</span> Your personalized feed is ready. Review recent questions and community activity.</div>
    <header className="sticky top-0 z-20 border-b border-[#d6d9dc] bg-white shadow-sm"><div className="mx-auto flex h-14 max-w-[1264px] items-center gap-5 px-4"><div className="flex shrink-0 items-center gap-1.5 text-xl font-bold tracking-tight"><Layers3 className="h-6 w-6 rotate-90" /><span>Stack<span className="font-normal">Overflow</span></span></div><nav className="hidden items-center gap-5 text-xs text-[#3b4045] lg:flex"><FakeLink>About</FakeLink><FakeLink>Products</FakeLink><FakeLink>Stack Internal</FakeLink></nav><div className="flex h-9 min-w-0 flex-1 items-center gap-2 rounded-md border border-[#babfc4] px-3 text-[#6a737c]"><Search className="h-4 w-4 shrink-0" /><span className="truncate text-sm">Search on Stack Overflow…</span></div><HelpCircle className="hidden h-4 w-4 text-[#5f6a72] sm:block" /><Inbox className="hidden h-4 w-4 text-[#5f6a72] sm:block" /><label className="flex shrink-0 items-center gap-2 text-xs text-[#3b4045]"><span className="hidden sm:inline">Work mode</span><Switch checked onCheckedChange={checked => { if (!checked) onExit(); }} aria-label="Exit work mode" /></label></div></header>

    <div className="mx-auto grid max-w-[1264px] lg:grid-cols-[164px_minmax(0,1fr)]">
      <aside className="hidden min-h-[calc(100vh-105px)] border-r border-[#d6d9dc] px-3 py-6 lg:block"><FakeNav icon={<Home />} label="Home" /><FakeNav icon={<MessageSquare />} label="Questions" active /><FakeNav icon={<Bot />} label="AI Assist" /><FakeNav icon={<Tags />} label="Tags" /><div className="h-5" /><FakeNav icon={<Bot />} label="Stack Overflow for Agents" /><div className="h-4" /><FakeNav icon={<Trophy />} label="Challenges" /><FakeNav icon={<MessageSquare />} label="Chat" /><FakeNav icon={<FileText />} label="Articles" /><FakeNav icon={<Users />} label="Users" /><div className="h-5" /><FakeNav icon={<Building2 />} label="Companies" /><FakeNav icon={<BriefcaseBusiness />} label="Developer Story" /><p className="mt-8 px-2 text-[11px] font-bold uppercase">Collectives</p><p className="px-2 pt-3 text-[11px] leading-4 text-[#6a737c]">Communities for your favorite technologies.<br /><span className="font-semibold underline">Explore all Collectives</span></p><p className="mt-8 px-2 text-[11px] font-bold uppercase">Stack Internal</p><div className="mt-3 flex gap-3 px-2 text-[#5f6a72]"><FileText className="h-4 w-4" /><Tags className="h-4 w-4" /><Bookmark className="h-4 w-4" /></div><p className="px-2 pt-4 text-[11px] leading-4 text-[#3b4045]">Stack Overflow for Teams is now called <strong>Stack Internal.</strong> Bring the best of human thought and AI automation together at your work.</p><button type="button" className="mt-4 w-full rounded-md bg-[#1b75d0] py-2 text-xs text-white">Try for free</button></aside>

      <main className="min-w-0 px-4 py-7 sm:px-6"><div className="flex items-start justify-between gap-6 border-b border-[#e3e6e8] pb-4"><div><h1 className="max-w-[780px] text-[27px] font-normal leading-[1.3] text-[#3b4045]">Unexpected variance in weekly projection results after scheduled processing</h1><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-[#6a737c]"><span>Year <strong className="font-normal text-[#3b4045]">{writeup.year}</strong></span><span>Week <strong className="font-normal text-[#3b4045]">{writeup.week}</strong></span><span>Author <strong className="font-normal text-[#3b4045]">{writeup.author.display_name}</strong></span></div></div><button type="button" className="hidden shrink-0 rounded-md bg-[#1b75d0] px-4 py-2.5 text-sm text-white sm:block">Ask Question</button></div>

        <div className="grid gap-6 pt-4 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="grid min-w-0 grid-cols-[44px_minmax(0,1fr)] gap-3"><aside className="flex flex-col items-center gap-2 text-[#3b4045]"><button type="button" aria-label="Up vote" className="grid h-10 w-10 place-items-center rounded-full border border-[#d6d9dc]"><ChevronUp className="h-6 w-6" /></button><span className="font-semibold">0</span><button type="button" aria-label="Down vote" className="grid h-10 w-10 place-items-center rounded-full border border-[#d6d9dc]"><ChevronDown className="h-6 w-6" /></button><Bookmark className="mt-1 h-5 w-5 text-[#9fa6ad]" /><History className="mt-1 h-5 w-5" /></aside><article className="min-w-0"><div className="text-[15px] leading-[1.55] text-[#232629] [&_b]:font-bold [&_div]:mb-4 [&_em]:italic [&_i]:italic [&_li]:mb-2 [&_ol]:mb-4 [&_ol]:list-decimal [&_ol]:pl-7 [&_p]:mb-4 [&_strong]:font-bold [&_u]:underline [&_ul]:mb-4 [&_ul]:list-disc [&_ul]:pl-7" dangerouslySetInnerHTML={{ __html: writeup.content_html }} /><div className="mt-8 flex flex-wrap gap-2"><span className="rounded bg-[#eff0f1] px-2 py-1.5 text-xs text-[#39739d]">javascript</span><span className="rounded bg-[#eff0f1] px-2 py-1.5 text-xs text-[#39739d]">production</span><span className="rounded bg-[#eff0f1] px-2 py-1.5 text-xs text-[#39739d]">debugging</span></div><div className="mt-8 flex justify-between text-xs text-[#6a737c]"><div className="flex gap-4"><FakeLink>Share</FakeLink><FakeLink>Edit</FakeLink><FakeLink>Follow</FakeLink></div><div className="rounded bg-[#d9eaf7] p-3 text-[#3b4045]"><p>asked in Week {writeup.week}</p><p className="mt-2 font-semibold text-[#0074cc]">{writeup.author.display_name}</p></div></div></article></section><WorkSidebar /></div>
      </main>
    </div>
  </div>;
}

function WorkSidebar() { return <aside className="hidden space-y-4 xl:block"><section className="rounded-md border border-[#6a5acd] bg-[#f7f7ff] p-4 text-sm"><h2 className="font-bold">Try Stack Overflow for Agents</h2><p className="font-bold">Verified knowledge for the agentic era</p><p className="mt-4 italic">Paste this into your AI coding assistant:</p><div className="mt-3 border border-[#d6d9dc] bg-white p-3 font-mono text-xs leading-4">Help me join Stack Overflow for Agents here. Read the documentation, then start onboarding.</div><p className="mt-3">Supports Claude Code, Cursor, Codex, Windsurf and more.</p><p className="mt-3 font-semibold text-[#0074cc]">Explore Stack Overflow for Agents</p></section><section className="overflow-hidden rounded-md border border-[#f1c40f] bg-[#fff7e0] text-sm"><div className="p-4"><h2 className="font-bold">The Overflow Blog</h2><p className="mt-3">✎ Java’s age is its AI superpower</p><p className="mt-3">✎ Observability that works for everyone</p></div><div className="border-t border-[#e6c36a] p-4"><h2 className="font-bold text-[#525960]">Featured on Meta</h2><p className="mt-3">▣ How we talk about ourselves (and to you)</p><p className="mt-3">▣ Policy: Generative AI is banned</p><p className="mt-3">▣ Developer Story is now available</p></div></section><section className="rounded-md border border-[#d6d9dc] p-4 text-sm"><h2 className="font-bold text-[#525960]">Related</h2><p className="mt-3 text-[#0074cc]">Handling unexpected output during scheduled jobs</p><p className="mt-3 text-[#0074cc]">Comparing results across weekly data sets</p></section></aside>; }
function FakeLink({ children }: { children: React.ReactNode }) { return <button type="button" className="hover:text-[#0c0d0e]">{children}</button>; }
function FakeNav({ icon, label, active }: { icon: React.ReactNode; label: string; active?: boolean }) { return <button type="button" className={`mb-1 flex w-full items-center gap-2 rounded-sm px-2 py-2 text-left text-[13px] ${active ? "bg-[#e3e6e8] font-bold text-[#0c0d0e]" : "text-[#3b4045] hover:bg-[#f1f2f3]"}`}><span className="[&_svg]:h-4 [&_svg]:w-4">{icon}</span>{label}</button>; }
