"use client";

import { FormEvent, useEffect, useState } from "react";
import { Copy, Plus, Users } from "lucide-react";
import { apiFetch } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

type ManagedUser = { id: string; username: string; display_name: string; role: "user" | "admin"; is_active: boolean; is_bootstrap: boolean; setup_pending: boolean };

export function UserManager() {
  const [users, setUsers] = useState<ManagedUser[]>([]); const [open, setOpen] = useState(false); const [setupUrl, setSetupUrl] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { try { setUsers(await apiFetch<ManagedUser[]>("/admin/users")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load users."); } }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); try { const result = await apiFetch<{ setup_token: string }>("/admin/users", { method: "POST", body: JSON.stringify({ username: form.get("username"), display_name: form.get("display_name"), role: form.get("role") }) }); setSetupUrl(`${window.location.origin}/setup-account?token=${encodeURIComponent(result.setup_token)}`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create account."); } finally { setSaving(false); } }
  return <section className="mt-6 overflow-hidden rounded-2xl border border-white/8 bg-card"><div className="flex flex-col gap-4 border-b border-white/8 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Users className="h-5 w-5" /></span><div><h2 className="font-bold">BTB accounts</h2><p className="text-sm text-slate-500">Create your permanent admin and league member accounts.</p></div></div><Dialog open={open} onOpenChange={value => { setOpen(value); if (!value) setSetupUrl(""); }}><DialogTrigger asChild><Button className="bg-primary font-bold text-primary-foreground"><Plus className="h-4 w-4" />Create account</Button></DialogTrigger><DialogContent className="border-white/10 bg-card"><DialogHeader><DialogTitle>Create a BTB account</DialogTitle><DialogDescription>The user receives a one-time setup link to choose their own password.</DialogDescription></DialogHeader>{setupUrl ? <div className="space-y-4"><div className="rounded-xl bg-white/5 p-4"><Label>One-time setup link</Label><p className="mt-2 break-all text-sm text-slate-300">{setupUrl}</p></div><Button className="w-full" onClick={() => navigator.clipboard.writeText(setupUrl)}><Copy className="h-4 w-4" />Copy setup link</Button><p className="text-xs text-slate-500">This credential expires in 48 hours and is only shown once.</p></div> : <form className="space-y-4" onSubmit={create}><div className="space-y-2"><Label htmlFor="new-username">Username</Label><Input id="new-username" name="username" required minLength={3} /></div><div className="space-y-2"><Label htmlFor="new-name">Display name</Label><Input id="new-name" name="display_name" required /></div><div className="space-y-2"><Label htmlFor="new-role">Role</Label><NativeSelect id="new-role" name="role" className="w-full"><NativeSelectOption value="user">User</NativeSelectOption><NativeSelectOption value="admin">Admin</NativeSelectOption></NativeSelect></div>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}<Button disabled={saving} className="w-full bg-primary font-bold text-primary-foreground">{saving ? "Creating…" : "Create account"}</Button></form>}</DialogContent></Dialog></div>{error && !open && <p className="px-5 py-4 text-sm text-red-300">{error}</p>}<div className="divide-y divide-white/7">{users.map(user => <div key={user.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[1fr_160px_130px] sm:items-center"><div><p className="font-semibold">{user.display_name}</p><p className="text-xs text-slate-500">@{user.username}{user.is_bootstrap ? " · environment bootstrap" : ""}</p></div><span className="text-sm capitalize text-slate-400">{user.role}</span><span className={`text-sm ${user.setup_pending ? "text-primary" : user.is_active ? "text-emerald-400" : "text-slate-500"}`}>{user.setup_pending ? "Setup pending" : user.is_active ? "Active" : "Disabled"}</span></div>)}</div></section>;
}
